### ISSUE TITLE
ALOHA2D is not launched from matlab system()

### ISSUE THREAD

**Issue by jhillairet** [jhillairet/ALOHA#1]
The matlab system() function returns the following results :

/Home/JH218595/codes/ALOHA/code_2D/couplage_2D/ALOHA2D_F90/ALOHA2D.OK: /Applications/Matlab_2010A/sys/os/glnxa64/libgcc_s.so.1: version `GCC_4.3.0' not found (required by /Home/JH218595/Spark3D/SPARK3D-1.6.3-full-Linux/dist/libgfortran.so.3)

which prevent running ALOHA2D correctly. However; launching the ALOHA2D.OK from the commande line works well.

**Comment by coobas** [comment]
Matlab sets its custom LD_LIBRARY_PATH when `system` is invoked (https://www.mathworks.com/matlabcentral/answers/181899-why-does-matlab-set-a-custom-ld_library_path-when-execting-system-on-linux?requestedDomain=www.mathworks.com,

**Comment by jhillairet** [comment]
Thanks for the hint :) !  

Matlab uses a CSH-type shell when using system() and thus is reading the .cshrc* files at each system() call. 

Having superseded my LD_LIBRARY_PATH for an other software to a a directory containing a libgfortran.so.3 compiled specifically for that software, matlab used that  libgfortran.so.3  instead of the system one... removing this additional path solves the bug.
